# Conda environment file for Six Keys Criticality
# Usage: conda env create -f environment.yml

name: sixkeys
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - networkx>=2.6
  - statsmodels>=0.13.0
  - tqdm>=4.62.0
  - pyyaml>=6.0
  - jupyter
  - ipywidgets
  - pip
  - pip:
    - numba>=0.56.0
    - sixkeys
    # Optional dependencies
    - plotly>=5.0.0
    - bokeh>=2.4.0
    # Development dependencies (uncomment if needed)
    # - pytest>=7.0.0
    # - pytest-cov>=4.0.0
    # - black>=22.0.0
    # - flake8>=4.0.0
    # - mypy>=0.950